# Generated by Django 5.0.1 on 2024-01-16 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
